# Generated by Django 6.0 on 2025-12-24 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('target_role', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('api_key_encrypted', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('portfolio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('resume_url', models.URLField(blank=True, max_length=500, null=True)),
                ('work_authorization', models.CharField(blank=True, choices=[('us_citizen', 'U.S. Citizen'), ('green_card', 'Green Card / Permanent Resident'), ('h1b', 'H-1B Visa'), ('h1b_transfer', 'H-1B (Need Transfer)'), ('opt', 'OPT'), ('opt_stem', 'OPT STEM Extension'), ('cpt', 'CPT'), ('f1', 'F-1 Student (Need Sponsorship)'), ('ead', 'EAD'), ('tn', 'TN Visa'), ('l1', 'L-1 Visa'), ('o1', 'O-1 Visa'), ('other_authorized', 'Other (Authorized to Work)'), ('need_sponsorship', 'Need Sponsorship')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('linkedin_job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_apply_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('has_easy_apply', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('not_interested', 'Not Interested'), ('apply_later', 'Apply Later'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('apply_method', models.CharField(blank=True, choices=[('easy_apply', 'Easy Apply'), ('external', 'External Website'), ('email', 'Email'), ('referral', 'Referral'), ('other', 'Other')], max_length=20, null=True)),
                ('hiring_contacts', models.JSONField(blank=True, default=list, null=True)),
                ('match_score', models.IntegerField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Post',
                'verbose_name_plural': 'Job Posts',
                'db_table': 'job_posts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_title', models.CharField(blank=True, max_length=200, null=True)),
                ('recipient_linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('message_type', models.CharField(choices=[('connection', 'Connection Request'), ('message', 'Direct Message'), ('inmail', 'InMail'), ('follow_up', 'Follow Up')], default='message', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('replied', 'Replied'), ('no_response', 'No Response')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_requests', to='api.jobpost')),
            ],
            options={
                'verbose_name': 'Connection Request',
                'verbose_name_plural': 'Connection Requests',
                'db_table': 'connection_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user_registered', 'User Registered'), ('user_login', 'User Login'), ('profile_updated', 'Profile Updated'), ('job_scanned', 'Job Scanned'), ('job_saved', 'Job Saved'), ('status_changed', 'Status Changed'), ('applied', 'Applied'), ('ai_analysis', 'AI Analysis'), ('message_generated', 'Message Generated'), ('message_sent', 'Message Sent')], max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='api.jobpost')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.CharField(blank=True, max_length=7, null=True)),
                ('end_date', models.CharField(blank=True, max_length=7, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experience',
                'db_table': 'work_experience',
                'ordering': ['order', '-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=200)),
                ('degree', models.CharField(blank=True, choices=[('high_school', 'High School'), ('associate', "Associate's Degree"), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('mba', 'MBA'), ('phd', 'Ph.D.'), ('jd', 'J.D.'), ('md', 'M.D.'), ('other', 'Other')], max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.CharField(blank=True, max_length=7, null=True)),
                ('end_date', models.CharField(blank=True, max_length=7, null=True)),
                ('is_graduated', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'db_table': 'education',
                'ordering': ['order', '-end_date'],
                'indexes': [models.Index(fields=['user', 'order'], name='education_user_id_0bd551_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['user', 'status'], name='job_posts_user_id_5ed94a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['user', 'scanned_at'], name='job_posts_user_id_ab12a7_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['company'], name='job_posts_company_3c4a31_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['match_score'], name='job_posts_match_s_819c21_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['linkedin_job_id'], name='job_posts_linkedi_98adf3_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobpost',
            constraint=models.UniqueConstraint(fields=('user', 'linkedin_url'), name='unique_job_per_user'),
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['user', 'status'], name='connection__user_id_eb4c5b_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['user', 'job'], name='connection__user_id_a4f6da_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['created_at'], name='connection__created_5e7102_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='activity_lo_user_id_d23b30_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='activity_lo_action_b49f28_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['user', 'order'], name='work_experi_user_id_01b99f_idx'),
        ),
    ]
