# Generated by Django 6.0 on 2025-12-25 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('template', models.TextField(help_text='Template with placeholders like {user_name}, {target_name}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('current_title', models.CharField(blank=True, max_length=255)),
                ('current_company', models.CharField(blank=True, max_length=255)),
                ('target_role', models.CharField(blank=True, max_length=255)),
                ('target_industry', models.CharField(blank=True, max_length=255)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('graduation_year', models.CharField(blank=True, max_length=10)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills')),
                ('bio', models.TextField(blank=True, help_text='Short bio or introduction')),
                ('connection_purpose', models.TextField(blank=True, help_text='Why user wants to connect (e.g., job seeking, networking, recruiting)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_name', models.CharField(max_length=255)),
                ('target_title', models.CharField(blank=True, max_length=255)),
                ('target_company', models.CharField(blank=True, max_length=255)),
                ('target_linkedin_url', models.URLField(blank=True)),
                ('message_sent', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Connection Request',
                'verbose_name_plural': 'Connection Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('messages_generated', models.IntegerField(default=0)),
                ('connections_sent', models.IntegerField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='api.userprofile')),
            ],
            options={
                'verbose_name': 'Usage Stats',
                'verbose_name_plural': 'Usage Stats',
                'ordering': ['-date'],
                'unique_together': {('user_profile', 'date')},
            },
        ),
    ]
